// <auto-generated />
namespace DP_60321_TROSHKO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class name_roleof_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name_roleof_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201803071032273_name_roleof_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
