// <auto-generated />
namespace DP_60321_TROSHKO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Offer_Date_notNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Offer_Date_notNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201802071519237_Offer_Date_notNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
