// <auto-generated />
namespace DP_60321_TROSHKO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class del_bind_post_comments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(del_bind_post_comments));
        
        string IMigrationMetadata.Id
        {
            get { return "201803071910159_del_bind_post_comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
