// <auto-generated />
namespace DP_60321_TROSHKO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bool_IsActual_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bool_IsActual_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201802221550041_bool_IsActual_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
