// <auto-generated />
namespace DP_60321_TROSHKO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addsidnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsidnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802262017507_add sid nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
